#version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: ".env.docker"
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
      - mongo

  db:
    image: postgres:17.0
    restart: always
    environment:
      POSTGRES_DB: ecoride
      POSTGRES_USER: ecoride
      POSTGRES_PASSWORD: 'ePStl]LoOamt8dZ2'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: 'ePStl]LoOamt8dZ2'
    ports:
      - "8081:80"
    depends_on:
      - db

  mongo:
    image: mongo:7.0
    restart: always
    volumes:
      - mongo_data:/data/db
    ports:
      - "27018:27017"
    # Si vous avez besoin d'authentification, dé commentez ces lignes :
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: username
    #   MONGO_INITDB_ROOT_PASSWORD: password

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8082:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
    depends_on:
      - mongo

volumes:
  postgres_data:
  mongo_data: