# fly.toml app configuration file pour ecorideback2

app = 'ecorideback2'
primary_region = 'cdg'

[build]
dockerfile = "Dockerfile"

[http_service]
internal_port = 80
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0

[env]
# Utilisez l'adresse interne de Fly pour accéder à MySQL
DATABASE_URL = "mysql://ecoride:ePStl]LoOamt8dZ2@ecoride-mysql.internal:3306/ecoride"

[experimental]
private_network = true

[deploy]
release_command = "php bin/console doctrine:migrations:migrate --no-interaction"