app = 'ecoride-mysql'
primary_region = 'cdg'

[build]
dockerfile = "Dockerfile.mysql"

[env]
MYSQL_ROOT_PASSWORD = "root"
MYSQL_DATABASE = "ecoride"
MYSQL_USER = "ecoride"
MYSQL_PASSWORD = "ePStl]LoOamt8dZ2"

[mounts]
source = "mysql_data"
destination = "/var/lib/mysql"

[services]
internal_port = 3306
protocol = "tcp"