on : push
name: Deploy website on AlwaysData on push
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: actions/checkout@v4
              
      - name: Sync files
        # You may pin to the exact commit or the version.
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          # ftp server
          server: ftp-ecorideback.alwaysdata.net
          # ftp username
          username: ecorideback_ftp
          # ftp password
          password: ${{ secrets.FTP_PASSWORD_ALWAYSDATA }}
          # Server port to connect to (read your web hosts docs)
          port: 990
          # protocol to deploy with - ftp, ftps, or ftps-legacy
          protocol: ftps
          # Folder to upload from, must end with trailing slash /
          #local-dir: # optional
          # Path to upload to on the server. Must end with trailing slash /
          server-dir: /
          # Path and name of the state file - this file is used to track which files have been deployed
          #state-name: # optional
          # Prints which modifications will be made with current config options, but doesnt actually make any changes
          #dry-run: # optional
          # Deletes ALL contents of server-dir, even items in excluded with exclude argument
          #dangerous-clean-slate: # optional
          # An array of glob patterns, these files will not be included in the publish/delete process
          exclude: |
            **/.git*
            **/.git*/**
          # How verbose should the information be - minimal, standard, or verbose
          log-level: verbose
          # strict or loose
          #security: # optional
          # Timeout in milliseconds for FTP operations
          timeout: 60000
