name: Publish Website SSH
on: 
  push:
jobs:
  web-deploy:
    name: 🚀 Deploy Website Every Commit
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get Latest Code
      uses: actions/checkout@v3
    
    - name: 📂 Sync Files
      uses: SamKirkland/web-deploy@v1
      with:
        target-server: ssh-ecorideback.alwaysdata.net
        remote-user: ecorideback
        private-ssh-key: ${{ secrets.SSH_KEY_RSA_ALWAYSDATA }}
        ssh-port: 22
        destination-path: /test/
        rsync-options: --dry-run --archive --verbose --compress --delete-after --human-readable --exclude=.git* --exclude=.git/ --exclude=README.md --exclude=readme.md --exclude=.gitignore
